### ISSUE TITLE
Corregir la clasificación taxonómica a nivel de especie

### ISSUE THREAD

**Issue by Terekab** [viktorKhan/aoa#16]
Corregir en la lista de aves de Albacete las columnas de la tabla "género" y "especie". 

Dos posibles soluciones:
1. puede solventarse poniendo en la columna "especie" la inicial del Nombre genérico.
Por ejemplo:
Ahora hay 2 columnas, una que pone Género y otra que pone Especie.
Género: Passer / Especie: domesticus
Sería:
Género Passer / Especie P. domesticus

2. unir las dos columnas en el epígrafe de Especie. Que no aparezca la columna de género no pasa nada, porque el género queda implícito en la columna de Especie.
Por ejemplo, quedaría:
Especie: Passer domesticus

**Comment by viktorKhan** [comment]
Corregida en el commit 174fbe081cdffb1320c3dd525f01710efe51f721
