### ISSUE TITLE
Añadir criterio de búsqueda de "Estudio"

### ISSUE THREAD

**Issue by Terekab** [viktorKhan/aoa#17]
Añadir en la búsqueda de citas, en la sección "¿Qué?", la opción de "Estudio" como un campo desplegable para buscar por tipo de estudio, por ejemplo para buscar los datos del censo de acuáticas de este invierno.

**Comment by viktorKhan** [comment]
Añadido en el commit b52502d99a85da105311683a8c3bf46badf5c19e
