### ISSUE TITLE
Añadir icono de fotografía en las tablas.

### ISSUE THREAD

**Issue by Terekab** [viktorKhan/aoa#19]
Añadir icono de fotografía en todas las tablas. Estaría bien saber en la tabla si la cita tiene foto o no.

**Comment by viktorKhan** [comment]
03a507e3118dfcfa40ba54a9d8ccc87bcc7a5f3c

**Comment by viktorKhan** [comment]
En la pantalla de búsqueda de citas no aparece el icono en las citas que tienen foto.

**Comment by viktorKhan** [comment]
Sólo era un problema de caché. Se ha borrado la caché y ya aparece el icono correctamente.
