### ISSUE TITLE
Ordenar la lista de aves por el código EURING

### ISSUE THREAD

**Issue by Terekab** [viktorKhan/aoa#20]
Mejor ordenar la lista por el código EURING, ya que como está ahora, sistemáticamente se quedan algunas especies mal ordenadas.

**Comment by viktorKhan** [comment]
He ordenado la lista de aves y existen algunas especies sin codigo Euring, de momento las he ignorado para que no aparezan pero, que hago con ellas? Lo dejo asi o las muestro al final?

**Comment by Terekab** [comment]
Efectivamente hay varias especies que no tienen código Euring, las especies exóticas, que originariamente no son europeas, y las híbridas. En la base de datos del anuario he actualizado sus códigos (en los híbridos he puesto el código genérico), con lo que ya está todo ordenado y arreglado.

**Comment by Terekab** [comment]
Me acabo de dar cuenta que el orden taxonómico que seguimos en el anuario es el de <b>AERC no el de Euring</b>. Si puedes, ordena la lista en el orden AERC y luego por Euring, ya que las subespecies tienen el mismo codigo AERC, pero cada subespecie tiene su propio código Euring. Siento no haberme dado cuenta antes.

**Comment by viktorKhan** [comment]
Hecho.

0e7e2d4465297dc68b2aedbdc492600e0920fff6
