### ISSUE TITLE
[Nueva cita] Avisar de que una cita esta repetida si coinciden fecha, lugar y especie

### ISSUE THREAD

**Issue by viktorKhan** [viktorKhan/aoa#7]
Ahora te dice que está repetida si coincide lugar+fecha+especie+observador. Mejor que te diga que está repetida si coincide lugar+fecha+especie.

Ha ocurrido una cita duplicada el 13-12-08 en Pinares del Júcar de una chocha perdiz. La cita es de Ángel y Juan Camacho, y en una cita la introduce Ángel y en otra el Anuario, y por eso no le dice que es cita repetida. Por eso quizás sea mejor que te diga cita repetida sin tener en cuenta el observador.

**Comment by viktorKhan** [comment]
No estoy seguro de si sería conveniente realizar esta modificación. Por ejemplo, si dos observadores que no se conocen, ven una especie en el mismo lugar en la misma fecha, ¿no sería esta una manera de corroborar que efectivamente esa cita es fiable? Puede que el número de individuos visto por uno o por otro varíe, o incluso que uno de ellos aporte más información en sus comentarios. A parte está el hecho de que sólo cuanta el primero que ha visto una especie en un lugar en una fecha y en mi opinión todos los datos cuentan. 

Otra cosa es que haya habido una confusión como parece ser este caso que describes, en tal caso se puede borrar una de las citas para evitar duplicados.

**Comment by Terekab** [comment]
Eso mismo que dices es lo que opinamos nosotros, aunque como se ha dado una duplicación de una cita por eso este cambio. Se podría dejar tal y como está, añadiendo un texto informativo cuando se suba una cita que coincida especie+fecha+lugar, de que ya existe una cita similar por el orbservador tal y que se asegure de que no sea la misma cita, o algo así.

**Comment by viktorKhan** [comment]
Ok, entonces puedo mostrar un aviso tal como ya se hace cuando creas un lugar que coincide con otro ya creado ¿no?

**Comment by Terekab** [comment]
Vale, con eso valdría.

**Comment by viktorKhan** [comment]
Corregido en el commit 62e746601aebb8ef27b98d0bf404109934ebb7ae
